version: 2

models:
  - name: stg_ccs_cdw_client
    description: >
      Stage table is with CCS client details

  - name: stg_claims_aggr
    description: >
      Stage table is with aggregated claims charge information      

  - name: stg_revenue_ccs_aggr
    description: >
      Stage table is with aggregated revenue information            

  - name: stg_revenue_claims_charge_aggr
    description: >
      Stage table is with claims charge information                  

  - name: stg_revenue_claims_realization_rate
    description: >
      Stage table is with claims realization rate information                        

  - name: stg_revenue_claims_revenue_aggr
    description: >
      Stage table is with claims revenue information                              

  - name: stg_revenue_claims_unique
    description: >
      Stage table is with distinct claims records

  - name: stg_snap_datetime
    description: >
      Stage table is to generate snapshot timestamp      