version: 2

models:
  - name: fact_claims_aggr
    description: >
      Fact table is for claim aggregation   

  - name: fact_claims_aggr_snap
    description: >
      Snapshot table is for claim aggregation                            

  - name: fact_comms_aggr
    description: >
      Fact table is for commissions aggregation 

  - name: fact_comms_aggr_snap
    description: >
      Snapshot table is for commissions aggregation                                    

  - name: fact_payments_aggr
    description: >
      Fact table is for payment aggregation                                   

  - name: fact_payments_aggr_snap
    description: >
      Snapshot table is for payment aggregation                                          

  