{{ config(materialized="table") }}

WITH stg_revenue AS (
SELECT 
CLIENT_ID,
    PRODUCT_TYPE_ID,
    SRC_SYS_ID AS SOURCE_SYSTEM_ID,
    BUSINESS_UNIT_ID,
    PROVIDER_ID,
    DATEKEY,
    TRAN_TYP,
    ACCOUNT_NAME,
    LEVEL_NAME,
    REVENUE_GL_ACCOUNT,
    REV_AMOUNT
from {{ref('stg_revenue_adaptive_aggr')}}
)
, PIVOTEDATA AS (
SELECT * FROM  stg_revenue
PIVOT (SUM(REV_AMOUNT) FOR TRAN_TYP IN (ANY ORDER BY TRAN_TYP))
)


, STG_REVENUE_AGGR AS (
SELECT
REVENUE_GL_ACCOUNT,CLIENT_ID,DATEKEY,PRODUCT_TYPE_ID
,BUSINESS_UNIT_ID,PROVIDER_ID,SOURCE_SYSTEM_ID,ACCOUNT_NAME,LEVEL_NAME,
SUM("'ACTUALS'") TOTAL_ACTUALS, SUM("'PLAN'") TOTAL_PLAN, SUM("'FORECAST'") TOTAL_FORECAST
FROM PIVOTEDATA
GROUP BY
REVENUE_GL_ACCOUNT,CLIENT_ID,DATEKEY,PRODUCT_TYPE_ID,BUSINESS_UNIT_ID,PROVIDER_ID, SOURCE_SYSTEM_ID,ACCOUNT_NAME,LEVEL_NAME
)
,stg_revenue_adaptive_aggr_Daily AS
(
SELECT
AGGR.CLIENT_ID,
AGGR.product_type_id,
AGGR.source_system_id,
AGGR.business_unit_id,
AGGR.PROVIDER_ID,
DR.DIMDATEKEY as dim_date_id,
AGGR.ACCOUNT_NAME,
AGGR.LEVEL_NAME,
AGGR.REVENUE_GL_ACCOUNT,
(AGGR.TOTAL_ACTUALS*DR.FINANCEDAYS)/FD.TOTAL_FINANCEDAYS AS
DAILYAMOUNT_ACTUALS,
(AGGR.TOTAL_PLAN*DR.FINANCEDAYS)/FD.TOTAL_FINANCEDAYS AS DAILYAMOUNT_PLAN,
(AGGR.TOTAL_FORECAST*DR.FINANCEDAYS)/FD.TOTAL_FINANCEDAYS AS DAILYAMOUNT_FORECAST,
--CASE WHEN DAILY_AMOUNT_FORECAST IS NULL THEN DAILYAMOUNT_PLAN ELSE DAILY_AMOUNT_FORECAST END AS DAILYAMOUNT_FORECAST,
concat(SOURCE_SYSTEM_ID, '_', CLIENT_ID) as srcuniqcd_dim_client,
concat(SOURCE_SYSTEM_ID, '_', PROVIDER_ID) as srcuniqcd_dim_provider,
concat('7', '_', PRODUCT_TYPE_ID) as srcuniqcd_dim_product_type,
concat('7', '_', SOURCE_SYSTEM_ID) as srcuniqcd_dim_source_system,
concat('7', '_', BUSINESS_UNIT_ID) as srcuniqcd_dim_business_unit
FROM
STG_REVENUE_AGGR AGGR
LEFT JOIN {{ source("caidwh_sources","dimdate") }}  DD ON
try_to_date(AGGR.DATEKEY, 'MONYYYY') =DD.DATEDAY
LEFT JOIN {{ source("caidwh_sources","dimdate") }}  DR ON
DD.DATEMONTHID=DR.DATEMONTHID AND DD.DATEYEAR=DR.DATEYEAR
LEFT JOIN (SELECT DATEMONTHID,DATEYEAR, SUM(FINANCEDAYS) AS TOTAL_FINANCEDAYS
FROM {{ source("caidwh_sources","dimdate") }}  GROUP BY 1,2 ) FD ON
DD.DATEMONTHID=FD.DATEMONTHID
AND DD.DATEYEAR=FD.DATEYEAR
)

SELECT * FROM stg_revenue_adaptive_aggr_Daily 