version: 2

models:
  - name: dim_business_unit
    description: >
      Mart table is for business unit dimension    

  - name: dim_business_unit_snap
    description: >
      Snapshot table is for business unit dimension

  - name: dim_client
    description: >
      Mart table is for business unit dimension

  - name: dim_client_snap
    description: >
      Snapshot table is for client dimension 
           
  - name: dim_exchrates
    description: >
      Mart table is for exchange rates dimension

  - name: dim_exchrates_snap
    description: >
      Snapshot table is for exchange rates dimension

  - name: dim_product_type
    description: >
      Mart table is for product type dimension 

  - name: dim_product_type_snap
    description: >
      Snapshot table is for product type dimension 

  - name: dim_provider
    description: >
      Mart table is for provider dimension

  - name: dim_source_system
    description: >
      Mart table is for source system dimension 

  - name: dim_source_system_snap
    description: >
      Snapshot table is for source system dimension 

  - name: dim_date_snap
    description: >
      Snapshot table is for date dimension 
  - name: dim_accounts
    description: >
      Mart table is with all accounts information from Adaptive                      
