{{ config(materialized='view') }}
 with FACTDATA AS (
   SELECT 
     dat."Date Day" DATEDAY,
    pps.dim_date_id,
    client.financeparent as PAYERID,
    DIM_PROVIDER_ID,
    CASE WHEN PRODUCT_TYPE_CATEGORY = 'Payments/Comms' THEN product.product_type else PRODUCT_TYPE_CATEGORY END PRODUCT_TYPE_CATEGORY,
    CASE
            WHEN sum(
                CASE
                    WHEN product_type = 'SAAS' then 0
                    ELSE ROUND(pps.VOLUME_AMOUNT, 2)
                END
            ) = 0 THEN NULL
            ELSE sum(
                CASE
                    WHEN product_type = 'SAAS' then 0
                    WHEN product_type IN ('Communication', 'Enrollment') and pps.VOLUME_AMOUNT <3  then 0
                    ELSE ROUND(pps.VOLUME_AMOUNT, 2)
                END
            )
        END CHARGED_AMOUNT,
        CASE
            WHEN sum(
                CASE
                    WHEN DIM_PROVIDER_ID = -1 THEN pps.NET_REVENUE_AMOUNT
                    ELSE ROUND(pps.GROSS_REVENUE_AMOUNT, 2)
                END
            ) = 0 THEN NULL
            ELSE sum(
                CASE
                    WHEN DIM_PROVIDER_ID = -1 THEN pps.NET_REVENUE_AMOUNT
                    ELSE ROUND(pps.GROSS_REVENUE_AMOUNT, 2)
                END
            )
        END REVENUE_AMOUNT
FROM {{ref('fact_revenue_aggr')}} pps
INNER JOIN {{ ref('dimdate')}} dat
    on dat.dim_date_id = pps.dim_date_id
INNER JOIN  {{ ref('dim_business_unit')}} business_unit
    on business_unit.dim_business_unit_id = pps.dim_business_unit_id
inner join  {{ ref("dim_product_type") }} product
    on product.dim_product_type_id = pps.dim_product_type_id
inner join {{ ref("dim_client") }} client
    on client.dim_client_id = pps.dim_client_id
WHERE
dat."Date Day" < DATE_TRUNC('MONTH',GETDATE())
and business_unit.BUSINESSUNITNAME in ('Payments', 'Communications')
and product.product_type not in ('Others')
and pps.SRC_UNIQ_CD <> '80914_3_2_2_1947_396555'
AND(product.PRODUCT_TYPE NOT IN ('ACH+-Settled','VCC-Settled','EPC Payer-Sponsored') OR
(product.PRODUCT_TYPE IN ('ACH+-Settled','VCC-Settled','EPC Payer-Sponsored') AND DIM_PROVIDER_ID <> -1))

GROUP BY
    dat."Date Day",
    pps.dim_date_id,
    client.financeparent,
    CASE WHEN PRODUCT_TYPE_CATEGORY = 'Payments/Comms' THEN product.product_type else PRODUCT_TYPE_CATEGORY END,
    DIM_PROVIDER_ID
),

ALLFACTCOMBOS AS (
SELECT d.DATEDAY, d.dim_date_id, p.PAYERID, p.PRODUCT_TYPE_CATEGORY, DIM_PROVIDER_ID FROM (SELECT DISTINCT DATEDAY, dim_date_id FROM FACTDATA) d
JOIN LATERAL (SELECT DISTINCT PAYERID, PRODUCT_TYPE_CATEGORY, DIM_PROVIDER_ID FROM FACTDATA) p ) 
,REVENUE AS (
SELECT
DATEDAY,
dim_date_id, 
PAYERID, 
PRODUCT_TYPE_CATEGORY, 
DIM_PROVIDER_ID,
DATEADD(year,1,DATEDAY) PYDATEDAY, 
DATEADD(year,2,DATEDAY) TWOPYDATEDAY,
DATEADD(month,1,DATEDAY) PMDATEDAY, 
DATEADD(month,2,DATEDAY) TWOPMDATEDAY, 
DATEADD(quarter,1,DATEDAY) PQDATEDAY, 
DATEADD(quarter,2,DATEDAY) TWOPQDATEDAY, 
REVENUE_AMOUNT REVENUE_AMOUNT,
CHARGED_AMOUNT CHARGED_AMOUNT,
IFNULL(REVENUE_AMOUNT/NULLIF(CHARGED_AMOUNT,0),0) PRICE
FROM FACTDATA
),

Cohorts AS (
SELECT CY.dim_date_id, CY.PAYERID, CY.PRODUCT_TYPE_CATEGORY, CY.DIM_PROVIDER_ID, CY.PYDATEDAY, CY.PMDATEDAY, CY.PQDATEDAY, CY.DATEDAY,
CASE WHEN CY.PRODUCT_TYPE_CATEGORY IN ('Communication', 'Enrollment') THEN
CASE WHEN IFNULL(CY.PRICE * PY.PRICE,0) <> 0 AND ROUND(IFNULL(CY.REVENUE_AMOUNT,0),0) <> 0 AND ROUND(IFNULL(PY.REVENUE_AMOUNT,0),0) <> 0 AND CY.CHARGED_AMOUNT > 2 AND PY.CHARGED_AMOUNT > 2 THEN IFNULL((CY.PRICE - PY.PRICE) * CY.CHARGED_AMOUNT,0) ELSE 0 END

ELSE
CASE WHEN IFNULL(CY.PRICE * PY.PRICE,0) <> 0 AND ROUND(IFNULL(CY.REVENUE_AMOUNT,0),0) <> 0 AND ROUND(IFNULL(PY.REVENUE_AMOUNT,0),0) <> 0 THEN  IFNULL((CY.PRICE - PY.PRICE) * CY.CHARGED_AMOUNT,0) ELSE 0 END END DELTAPRICEYEAR,
CASE WHEN CY.PRODUCT_TYPE_CATEGORY IN ('Communication', 'Enrollment') THEN
CASE WHEN IFNULL(CY.PRICE * PQ.PRICE,0) <> 0 AND ROUND(IFNULL(CY.REVENUE_AMOUNT,0),0) <> 0 AND ROUND(IFNULL(PQ.REVENUE_AMOUNT,0),0) <> 0 AND CY.CHARGED_AMOUNT > 2 AND PQ.CHARGED_AMOUNT > 2 THEN IFNULL((CY.PRICE - PQ.PRICE) * CY.CHARGED_AMOUNT,0) ELSE 0 END
ELSE
CASE WHEN IFNULL(CY.PRICE * PQ.PRICE,0) <> 0 AND ROUND(IFNULL(CY.REVENUE_AMOUNT,0),0) <> 0 AND ROUND(IFNULL(PQ.REVENUE_AMOUNT,0),0) <> 0 THEN  IFNULL((CY.PRICE - PQ.PRICE) * CY.CHARGED_AMOUNT,0) ELSE 0 END END DELTAPRICEQUARTER,

CASE WHEN CY.PRODUCT_TYPE_CATEGORY IN ('Communication', 'Enrollment') THEN
CASE WHEN IFNULL(CY.PRICE * PM.PRICE,0) <> 0 AND ROUND(IFNULL(CY.REVENUE_AMOUNT,0),0) <> 0 AND ROUND(IFNULL(PM.REVENUE_AMOUNT,0),0) <> 0 AND CY.CHARGED_AMOUNT > 2 AND PM.CHARGED_AMOUNT > 2 THEN IFNULL((CY.PRICE - PM.PRICE) * CY.CHARGED_AMOUNT,0) ELSE 0 END
ELSE
CASE WHEN IFNULL(CY.PRICE * PM.PRICE,0) <> 0 AND ROUND(IFNULL(CY.REVENUE_AMOUNT,0),0) <> 0 AND ROUND(IFNULL(PM.REVENUE_AMOUNT,0),0) <> 0 THEN  IFNULL((CY.PRICE - PM.PRICE) * CY.CHARGED_AMOUNT,0) ELSE 0 END END DELTAPRICEMONTH,

CASE WHEN CY.PRODUCT_TYPE_CATEGORY IN ('Communication', 'Enrollment') THEN
CASE WHEN IFNULL(CY.CHARGED_AMOUNT * PY.CHARGED_AMOUNT,0) <> 0 AND ROUND(IFNULL(CY.REVENUE_AMOUNT,0),0) <> 0 AND ROUND(IFNULL(PY.REVENUE_AMOUNT,0),0) <> 0 AND CY.CHARGED_AMOUNT > 2 AND PY.CHARGED_AMOUNT > 2 THEN IFNULL((CY.CHARGED_AMOUNT - PY.CHARGED_AMOUNT) * PY.Price,0) ELSE 0 END
ELSE
CASE WHEN IFNULL(CY.CHARGED_AMOUNT * PY.CHARGED_AMOUNT,0) <> 0 AND ROUND(IFNULL(CY.REVENUE_AMOUNT,0),0) <> 0 AND ROUND(IFNULL(PY.REVENUE_AMOUNT,0),0) <> 0 THEN  IFNULL((CY.CHARGED_AMOUNT - PY.CHARGED_AMOUNT) * PY.Price,0) ELSE 0 END END DELTAVOLUMEYEAR,

CASE WHEN CY.PRODUCT_TYPE_CATEGORY IN ('Communication', 'Enrollment') THEN
CASE WHEN IFNULL(CY.CHARGED_AMOUNT * PQ.CHARGED_AMOUNT,0) <> 0 AND ROUND(IFNULL(CY.REVENUE_AMOUNT,0),0) <> 0 AND ROUND(IFNULL(PQ.REVENUE_AMOUNT,0),0) <> 0 AND CY.CHARGED_AMOUNT > 2 AND PQ.CHARGED_AMOUNT > 2 THEN IFNULL((CY.CHARGED_AMOUNT - PQ.CHARGED_AMOUNT) * PQ.PRICE,0) ELSE 0 END
ELSE
CASE WHEN IFNULL(CY.CHARGED_AMOUNT * PQ.CHARGED_AMOUNT,0) <> 0 AND ROUND(IFNULL(CY.REVENUE_AMOUNT,0),0) <> 0 AND ROUND(IFNULL(PQ.REVENUE_AMOUNT,0),0) <> 0 THEN  IFNULL((CY.CHARGED_AMOUNT - PQ.CHARGED_AMOUNT) * PQ.PRICE,0) ELSE 0 END END DELTAVOLUMEQUARTER,

CASE WHEN CY.PRODUCT_TYPE_CATEGORY IN ('Communication', 'Enrollment') THEN
CASE WHEN IFNULL(CY.CHARGED_AMOUNT * PM.CHARGED_AMOUNT,0) <> 0 AND ROUND(IFNULL(CY.REVENUE_AMOUNT,0),0) <> 0 AND ROUND(IFNULL(PM.REVENUE_AMOUNT,0),0) <> 0 AND CY.CHARGED_AMOUNT > 2 AND PM.CHARGED_AMOUNT > 2 THEN IFNULL((CY.CHARGED_AMOUNT - PM.CHARGED_AMOUNT) * PM.PRICE,0) ELSE 0 END
ELSE
CASE WHEN IFNULL(CY.CHARGED_AMOUNT * PM.CHARGED_AMOUNT,0) <> 0 AND ROUND(IFNULL(CY.REVENUE_AMOUNT,0),0) <> 0 AND ROUND(IFNULL(PM.REVENUE_AMOUNT,0),0) <> 0 THEN  IFNULL((CY.CHARGED_AMOUNT - PM.CHARGED_AMOUNT) * PM.PRICE,0) ELSE 0 END END DELTAVOLUMEMONTH,

CASE WHEN ROUND(IFNULL(CY.REVENUE_AMOUNT,0),0) <> 0 AND ROUND(IFNULL(PY.REVENUE_AMOUNT,0),0) <> 0 AND ROUND(IFNULL(TwoPY.REVENUE_AMOUNT,0),0) <> 0 THEN 1 ELSE 0 END YEARBASEFLAG,
CASE WHEN ROUND(IFNULL(CY.REVENUE_AMOUNT,0),0) <> 0 AND ROUND(IFNULL(PY.REVENUE_AMOUNT,0),0) <> 0 AND ROUND(IFNULL(TwoPY.REVENUE_AMOUNT,0),0) = 0 THEN 1 ELSE 0 END YEARRAMPINGFLAG,
CASE WHEN ROUND(IFNULL(CY.REVENUE_AMOUNT,0),0) <> 0 AND ROUND(IFNULL(PM.REVENUE_AMOUNT,0),0) <> 0 AND ROUND(IFNULL(TwoPM.REVENUE_AMOUNT,0),0) <> 0 THEN 1 ELSE 0 END MONTHBASEFLAG,
CASE WHEN ROUND(IFNULL(CY.REVENUE_AMOUNT,0),0) <> 0 AND ROUND(IFNULL(PM.REVENUE_AMOUNT,0),0) <> 0 AND ROUND(IFNULL(TwoPM.REVENUE_AMOUNT,0),0) = 0 THEN 1 ELSE 0 END MONTHRAMPINGFLAG,
CASE WHEN ROUND(IFNULL(CY.REVENUE_AMOUNT,0),0) <> 0 AND ROUND(IFNULL(PQ.REVENUE_AMOUNT,0),0) <> 0 AND ROUND(IFNULL(TwoPQ.REVENUE_AMOUNT,0),0) <> 0 THEN 1 ELSE 0 END QUARTERBASEFLAG,
CASE WHEN ROUND(IFNULL(CY.REVENUE_AMOUNT,0),0) <> 0 AND ROUND(IFNULL(PQ.REVENUE_AMOUNT,0),0) <> 0 AND ROUND(IFNULL(TwoPQ.REVENUE_AMOUNT,0),0) = 0 THEN 1 ELSE 0 END QUARTERRAMPINGFLAG,
CASE WHEN ROUND(IFNULL(CY.REVENUE_AMOUNT,0),0) <> 0 OR ROUND(IFNULL(PY.REVENUE_AMOUNT,0),0) <> 0 OR ROUND(IFNULL(PM.REVENUE_AMOUNT,0),0) <> 0 OR ROUND(IFNULL(PQ.REVENUE_AMOUNT,0),0) <> 0 then 1 else 0 END ROWFILTERFLAG

FROM REVENUE CY 
LEFT JOIN REVENUE PY on CY.DATEDAY = PY.PYDATEDAY and CY.PAYERID = PY.PAYERID and CY.PRODUCT_TYPE_CATEGORY = PY.PRODUCT_TYPE_CATEGORY and CY.DIM_PROVIDER_ID = PY.DIM_PROVIDER_ID
LEFT JOIN REVENUE TWOPY on CY.DATEDAY = TWOPY.TWOPYDATEDAY and CY.PAYERID = TWOPY.PAYERID and CY.PRODUCT_TYPE_CATEGORY = TWOPY.PRODUCT_TYPE_CATEGORY and CY.DIM_PROVIDER_ID = TWOPY.DIM_PROVIDER_ID
LEFT JOIN REVENUE PM on CY.DATEDAY = PM.PMDATEDAY and CY.PAYERID = PM.PAYERID and CY.PRODUCT_TYPE_CATEGORY = PM.PRODUCT_TYPE_CATEGORY and CY.DIM_PROVIDER_ID = PM.DIM_PROVIDER_ID
LEFT JOIN REVENUE TWOPM on CY.DATEDAY = TWOPM.TWOPMDATEDAY and CY.PAYERID = TWOPM.PAYERID and CY.PRODUCT_TYPE_CATEGORY = TWOPM.PRODUCT_TYPE_CATEGORY and CY.DIM_PROVIDER_ID = TWOPM.DIM_PROVIDER_ID
LEFT JOIN REVENUE PQ on CY.DATEDAY = PQ.PQDATEDAY and CY.PAYERID = PQ.PAYERID and CY.PRODUCT_TYPE_CATEGORY = PQ.PRODUCT_TYPE_CATEGORY and CY.DIM_PROVIDER_ID = PQ.DIM_PROVIDER_ID
LEFT JOIN REVENUE TWOPQ on CY.DATEDAY = TWOPQ.TWOPQDATEDAY and CY.PAYERID = TWOPQ.PAYERID and CY.PRODUCT_TYPE_CATEGORY = TWOPQ.PRODUCT_TYPE_CATEGORY and TWOPQ.DIM_PROVIDER_ID = PY.DIM_PROVIDER_ID

)

,factpvm_provider_pps as
( 
SELECT t1.DATEDAY, 
t1.dim_date_id,
t1.PAYERID, 
t1.PRODUCT_TYPE_CATEGORY, 
t1.DIM_PROVIDER_ID,
t2.REVENUE_AMOUNT, 
t2.CHARGED_AMOUNT, 
COCY.DELTAPRICEYEAR,
COCY.DELTAPRICEQUARTER,
COCY.DELTAPRICEMONTH,
COCY.DELTAVOLUMEYEAR,
COCY.DELTAVOLUMEQUARTER,
COCY.DELTAVOLUMEMONTH,
IFNULL(COCY.YEARBASEFLAG,0) AS YEARBASEFLAG, 
IFNULL(COCY.YEARRAMPINGFLAG,0) AS YEARRAMPINGFLAG, 
IFNULL(COCY.QUARTERBASEFLAG,0) AS QUARTERBASEFLAG, 
IFNULL(COCY.QUARTERRAMPINGFLAG,0) AS QUARTERRAMPINGFLAG,

IFNULL(COCY.MONTHBASEFLAG,0) AS MONTHBASEFLAG, 
IFNULL(COCY.MONTHRAMPINGFLAG,0) AS MONTHRAMPINGFLAG, 
IFNULL(COHPY.YEARBASEFLAG,0) PYYEARBASEFLAG, 
IFNULL(COHPY.YEARRAMPINGFLAG,0) PYYEARRAMPINGFLAG,
IFNULL(COHPQ.QUARTERBASEFLAG,0) PQQUARTERBASEFLAG,
IFNULL(COHPQ.QUARTERRAMPINGFLAG,0) PQQUARTERRAMPINGFLAG,
IFNULL(COHPM.MONTHBASEFLAG,0) PMMONTHBASEFLAG, 
IFNULL(COHPM.MONTHRAMPINGFLAG,0) PMMONTHRAMPINGFLAG
FROM ALLFACTCOMBOS t1

LEFT JOIN REVENUE t2 on t1.dim_date_id = t2.dim_date_id and t1.PAYERID = t2.PAYERID and t1.PRODUCT_TYPE_CATEGORY = t2.PRODUCT_TYPE_CATEGORY and t1.DIM_PROVIDER_ID = t2.DIM_PROVIDER_ID
LEFT JOIN COHORTS COCY on t1.dim_date_id = COCY.dim_date_id and t1.PAYERID = COCY.PAYERID and t1.PRODUCT_TYPE_CATEGORY = COCY.PRODUCT_TYPE_CATEGORY and t1.DIM_PROVIDER_ID = COCY.DIM_PROVIDER_ID
LEFT JOIN COHORTS COHPY on t1.DATEDAY = DATEADD(year,-1,COHPY.DATEDAY) and t1.PAYERID = COHPY.PAYERID and t1.PRODUCT_TYPE_CATEGORY = COHPY.PRODUCT_TYPE_CATEGORY and t1.DIM_PROVIDER_ID = COHPY.DIM_PROVIDER_ID
LEFT JOIN COHORTS COHPQ on t1.DATEDAY = DATEADD(quarter,-1,COHPQ.DATEDAY) and t1.PAYERID = COHPQ.PAYERID and t1.PRODUCT_TYPE_CATEGORY = COHPQ.PRODUCT_TYPE_CATEGORY and t1.DIM_PROVIDER_ID = COHPQ.DIM_PROVIDER_ID
LEFT JOIN COHORTS COHPM on t1.DATEDAY = DATEADD(month,-1,COHPM.DATEDAY) and t1.PAYERID = COHPM.PAYERID and t1.PRODUCT_TYPE_CATEGORY = COHPM.PRODUCT_TYPE_CATEGORY and t1.DIM_PROVIDER_ID = COHPM.DIM_PROVIDER_ID
WHERE COCY.ROWFILTERFLAG = 1
)

select * from factpvm_provider_pps
