version: 2

models:
  - name: DIM_business_unit
    description: >
      Consolidated view is for business unit dimension

  - name: DIM_product_type
    description: >
      Consolidated view is for product type dimension      

  - name: DIM_source_system
    description: >
      Consolidated view is for source system dimension            
  
  - name: DIM_exchrates
    description: >
      Consolidated view is for exchange rates dimension
      
  - name: dimclient
    description: >
      PVM view is for client dimension

  - name: dimclient_sapphire
    description: >
      PVM view is for client dimension of Sapphire business      

  - name: dimdate
    description: >
      PVM view is for date dimension

  - name: dimpayer
    description: >
      PVM view is for payer dimension      

  - name: dimproducttype
    description: >
      PVM view is for product type dimension            

  - name: dimproducttype_pps
    description: >
      PVM view is for product type dimension of PPS

  - name: dimproducttype_sapphire
    description: >
      PVM view is for product type dimension of Sapphire business

  - name: factpvm_ccs
    description: >
      PVM view is for CCS fact data      

  - name: factpvm_pps
    description: >
      PVM view is for PPS fact data            

  - name: factpvm_sapphire
    description: >
      PVM view is for fact data of Sapphire business