version: 2

models:
  - name: intr_metrics_user
    description: >
      Intermediate table is for metrics_user

  - name: intr_metrics_category
    description: >
      Intermediate table is for metrics_category    

  - name: intr_metrics
    description: >
      Intermediate table is for metrics
  - name: intr_metrics_kpi
    description: >
      Intermediate table is for metrics kpi