version: 2

models:
  - name: stg_revenue_vpay
    description: >
      Stage table is with VPAY revenue information

  - name: stg_vpay_client
    description: >
      Stage table is with VPAY client information      