version: 2

models:
  - name: stg_comms_aggr
    description: >
      Stage table is with DOCS commission aggregation

  - name: stg_docs_client
    description: >
      Stage table is with DOCS client information

  - name: stg_revenue_docs
    description: >
      Stage table is with DOCS revenue information      

  - name: stg_revenue_docs_aggr
    description: >
      Stage table is with DOCS revenue aggregation            